server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false

spring.mail.host=smtp.gmail.com
spring.mail.username=${MAIL_USERNAME:vamsikathi16@gmail.com}
spring.mail.password=${MAIL_PASSWORD:rpoc dpsd swhl yjdx}
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

rupee.sign=${RUPEE_SIGN:&#8377;}

